# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wIxUwYa58xCVXhDS-XMmDG_xPUOI7gaT
"""

# Import libraries
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# Load training data
url_train = "https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv"
train_data = pd.read_csv(url_train)

# Separate target and features
y = train_data["meal"]
X = train_data.drop(columns=["meal"])

# Encode categorical variables
X = pd.get_dummies(X)
X = X.fillna(0)

# Define and fit model
model = RandomForestClassifier(random_state=42)
modelFit = model.fit(X, y)  # ✅ Fit result stored in modelFit

# Load test data
url_test = "https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3test.csv"
test_data = pd.read_csv(url_test)

# Encode test data
test_data = pd.get_dummies(test_data)
test_data = test_data.reindex(columns=X.columns, fill_value=0)
test_data = test_data.fillna(0)

# Predict
raw_pred = modelFit.predict(test_data)
pred = [int(p) for p in raw_pred]  # ✅ Convert to plain list of 0/1 ints

# Final checks
print("✅ modelFit type:", type(modelFit))
print("✅ Number of predictions:", len(pred))
print("✅ Sample predictions:", pred[:10])