# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wIxUwYa58xCVXhDS-XMmDG_xPUOI7gaT
"""

# Import libraries
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# Load training data
url_train = "https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv"
train_data = pd.read_csv(url_train)

# Separate target
y = train_data["meal"]
X = train_data.drop(columns=["meal"])

# Convert categorical variables to dummy variables (one-hot encoding)
X = pd.get_dummies(X)

# Fill missing values
X = X.fillna(0)

# Define the model
model = RandomForestClassifier(random_state=42)

# Fit the model
model.fit(X, y)

# Store fitted model
modelFit = model

# Load test data
url_test = "https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3test.csv"
test_data = pd.read_csv(url_test)

# One-hot encode test data to match training
test_data = pd.get_dummies(test_data)

# Align test data columns to training columns (fill missing columns with 0)
test_data = test_data.reindex(columns=X.columns, fill_value=0)

# Fill any remaining NaNs
test_data = test_data.fillna(0)

# Predict
raw_pred = modelFit.predict(test_data)

# Convert to list of integers
pred = [int(p) for p in raw_pred]

# Print result
print("Number of predictions:", len(pred))
print("Sample predictions:", pred[:10])